# This is an example config file showing how to set it up
# Your real config file should go in ~/.config/grade/config.toml

credentials = "ssh"
digital = "/mnt/c/Users/usf/Documents/Digital/digital.jar"
org = "cs-315-03-20f"
project = "project02"
students = [
    "phpeterson-usf",
    "gdbenson",
]
